version: '3.8'

services:
  app:
    build:
      context: ./app 
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    volumes:
      - ./app:/app  
    env_file:
      - ./app/config/.env  